{% set name = "ml_tooling" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6ffce786a316c8b375c18f79692d0884f21135e946b425e34cfd99a9821afa3
build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - numpy
    - scikit-learn
    - gitpython
    - matplotlib
    - pyyaml
    - joblib

test:
  imports:
    - ml_tooling
    - ml_tooling.plots

about:
  home: http://github.com/andersbogsnes/ml_tooling
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Modelling framework to simplify machine learning workflows'

  description: |
    ML Tooling is a framework for standardising modelling tasks. It includes many utilities
    for plotting and viz as well as standardised interfaces for training and testing

extra:
  recipe-maintainers:
    - andersbogsnes
