{% set name = "ml_tooling" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 809ca1bfa8349db8c620bd34b46fe3331f2d9b0bee2b027ba60bc5857c3c108f
build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pandas
    - scikit-learn
    - matplotlib
    - pyyaml
    - joblib
    - sqlalchemy
    - attrs


test:
  imports:
    - ml_tooling
    - ml_tooling.plots

about:
  home: http://github.com/andersbogsnes/ml_tooling
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Modelling framework to simplify machine learning workflows'

  description: |
    ML Tooling is a framework for standardising modelling tasks. It includes many utilities
    for plotting and viz as well as standardised interfaces for training and testing

extra:
  recipe-maintainers:
    - andersbogsnes
