{% set name = "ml_tooling" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f0213f52cd8cff1ec9dc56aa7f21964a2af6c4f050ab83c1f567fa7afad72d9
build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pandas
    - scikit-learn
    - matplotlib
    - pyyaml
    - joblib
    - sqlalchemy
    - attrs


test:
  imports:
    - ml_tooling
    - ml_tooling.plots

about:
  home: http://github.com/andersbogsnes/ml_tooling
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Modelling framework to simplify machine learning workflows'

  description: |
    ML Tooling is a framework for standardising modelling tasks. It includes many utilities
    for plotting and viz as well as standardised interfaces for training and testing

extra:
  recipe-maintainers:
    - andersbogsnes
