travis:
  secure:
    BINSTAR_TOKEN: xJEi9D/b1LsWXtnAOeePTexrGnCW3O1L3JerUGOK6PaFKqpdFpKAQ6/ramhCUutu7XhltuAssu4ZpUW32qi5DxpttT1BWVCoc7qH2wBHJInXEbRfQ+a/+X5doc1w9a5Dlp5vnVQS8R7OGMhbDbcw6RXJC4aDdMivjGq8bv7GLUmkRbcbeqc4hwQZ54xU6mrtanX05YRQELybKhYRZ1qEceJ2tpjoAW6CF1VHzV9OpBAg1raX787XBKUQawLdYREOWKrLDfBqxbhVzuQOT7WYbPUenhhG3Dezmgye8qx3tbt/Nk9iVDMqfh8MbGKaPtcZGQ3g1HcRu1BzZ0NYLuJsJo7EEV1xxMo4CQCu0swLwn6xtu0LZU85DizvRIjKvMW8UBuwmIeM58AhxMC8yQPT5JXZZutbu+18RFsrhNIyK8whV2XsMA55icx0KevaPU66EWqkTxygEZAaQTGAgggCs+R2DJ1JWuK/8ZhPihSl4ZmGRIm1WyBBQQlMR2AILzdVgPh6YVjCb6WNP8vh7HsLUC+7ADtuqMZkqslxkvF1rtmuoT1x4APK117+B4PgOGvlpCHS0yzt6h9FKjFZy/kmw9EoPKztKrJlTpVdCEWFVGAxREyqPxkv+Ewk6HARKaRSM7wkIKQbt3DtUXgAwUpvUmYlbpNVen7KVBvrpVey4wI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
